nginx:
  image: nginx
  volumes:
    - /container/docker_registry/nginx.conf:/etc/nginx/conf.d/nginx.conf
    - /container/docker_registry/docker-registry.conf:/etc/nginx/docker-registry.conf
    - /container/docker_registry/cert.pem:/etc/ssl/certs/docker-registry
    - /container/docker_registry/key.pem:/etc/ssl/private/docker-registry
  links:
    - registrybackend
  hostname: registry.service.lab.mu
  environment:
    SERVICE_NAME: registry
registrybackend:
  image: registry
  expose:
    - "5000"
  environment:
    - SETTINGS_FLAVOR=dev
    - STORAGE_PATH=/registry
    - SERVICE_IGNORE=true
  volumes:
    - /container/docker_registry/data:/registry
